#%RAML 1.0 NamedExample
{
    "CustomerName": "Dinesh",
    "BillingStreet": "govind Street",
    "BillingCity": "chennai",
    "BillingState": "tamilnadu",
    "BillingCountry": "India",
    "BillingPostalCode": "600112"
  }