#%RAML 1.0 NamedExample
[{
  "Name": "Dhoni",
  "BillingStreet": "Vijay Street",
  "BillingCity": "Trichy",
  "BillingState": "TamilNadu",
  "BillingCountry": "India",
  "BillingPostalCode": "600112"
}]