#%RAML 1.0 NamedExample
{
  "Name": "Dhoni",
  "External__id": "12345",
  "BillingStreet": "Vijay Street",
  "BillingCity": "Trichy",
  "BillingState": "TamilNadu",
  "BillingCountry": "India",
  "BillingPostalCode": "600112"
}